name:                haskell-servant-web-app
version:             0.1.0.0
github:              "bewrrrie/haskell-servant-web-app"
license:             MIT
author:              "Vadim Leshkov"
maintainer:          "vadim.leshkov@protonmail.com"
copyright:           "Vadim Leshkov"
category:            Web
extra-source-files:
- README.md
description:         Please see the README

dependencies:
- base >= 4.7 && < 5
- text
- time
- aeson
- servant
- servant-client
- http-client
- http-client-tls

ghc-options:
- -Wall
- -Werror
- -Wcompat
- -Wincomplete-uni-patterns

library:
  source-dirs: src

executables:
  app-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-servant-web-app

tests:
  app-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-servant-web-app
    - doctest
